src/routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/about-us', 'HomeController@about_us')->name('about.us');
Route::get('/contact-us', 'HomeController@contact_us')->name('contact.us');
Route::post('/contact-us/save', 'HomeController@contactSave')->name('contact.save');
Route::get('/faq', 'HomeController@faq')->name('faq');
Route::get('/user-register', 'HomeController@register')->name('user.register');
Route::get('/user-login','HomeController@login')->name('user.login');


Route::get('/aws/event-test' ,'AWSCloudWatchController@eventTest')->name('aws.event');


Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@dashboard')->name('dashboard');
Route::get('/debug', 'HomeController@debug')->name('debug');

Route::get('/email-testing', 'HomeController@emailTesting')->name('email.test');
Route::post('/email-get', 'HomeController@emailGet')->name('email.get');

Route::get('/register/{id}/info', 'UserController@info')->name('register.info');
Route::post('/register-info/save', 'UserController@store_info')->name('register.info.store');
Route::any('/non-wholesalers/{id}/message', 'UserController@messageView')->name('register.message');
Route::any('/acceptTerms', 'HomeController@ajaxTermsCondition')->name('acceptTerms');
Route::any('/mail-jobs', 'JobController@processQueue')->name('job.expire-trails');
Route::post('/email-user' , 'HomeController@emailUser')->name('email.user');


Route::any('/send-verify-code', 'PhoneVerificationController@ajaxSendVerifyCode')->name('verifyphone.send');
Route::any('/verify-code', 'PhoneVerificationController@verify')->name('verifyphone.verify');




//Route::get('/save-purchase', 'PurchaseController@save_purchase')->name('save.purchase');



Route::prefix('/dashboard')->middleware('role:Admin','auth')->group(function () {

	//User Management Routing.
	Route::resource('user', 'UserController', ['except' => ['show']]);

	Route::any('user/export','UserController@export')->name('user.export');
	Route::any('users/retailers','UserController@nonwholesalers')->name('user.retailers');

	Route::any('user/delete/{id}','UserController@delete')->name('user.delete');
	Route::any('user/active/{id}','UserController@active')->name('user.active');
	Route::any('user/inactive/{id}','UserController@inactive')->name('user.inactive');
	Route::any('user/edit/{id}','UserController@editUser')->name('user.edit');
	Route::post('user/search','UserController@search')->name('user.search');




	Route::get('settings', 'SettingController@index')->name('settings');
	Route::get('email-settings', 'SettingController@emailSettings')->name('settings.email');
	Route::post('update-options', 'SettingController@update_options')->name('settings.update');


});

Route::prefix('/dashboard')->middleware('auth')->group(function () {

	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

});

Route::prefix('/dashboard')->middleware('role:User','auth')->group(function () {

	Route::any('api-portal-settings', 'UserSettingController@index')->name('user.settings');
	Route::post('settings/create', 'UserSettingController@create')->name('user.settings.create');
	Route::post('settings/update', 'UserSettingController@update')->name('user.settings.update');

    Route::any('/saas-agreement','UserController@agreementPdf')->name('pdf.agreement');

	Route::get('purchase', 'PurchaseController@index')->name('purchase');
	Route::get('purchase/{id}', 'PurchaseController@purchase_items')->name('purchase.items');


});

src/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Database\Eloquent\Builder;
use Twilio\Rest\Client;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'status', 'pharmacy_name',
        'pharmacy_phone', 'pharmacy_email', 'pbs_number', 'address',
        'role', 'user_state', 'trail_expires', //'verification_code'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        //'phone_verified_at' => 'datetime',
    ];

    public function hasVerifiedPhone()
    {
        return ! is_null($this->phone_verified_at);
    }

    public function markPhoneAsVerified()
    {
        return $this->forceFill([
            'phone_verified_at' => $this->freshTimestamp(),
        ])->save();
    }

    public function callToVerify()
    {
        $code = random_int(100000, 999999);

        $this->forceFill([
            'verification_code' => $code
        ])->save();

        $client = new Client(env('TWILIO_SID'), env('TWILIO_AUTH_TOKEN'));

        $client->calls->create(
            $this->phone,
            "+15306658566", // REPLACE WITH YOUR TWILIO NUMBER
            ["url" => "http://your-ngrok-url>/build-twiml/{$code}"]
        );
    }

    protected static function boot() {
        parent::boot();

        static::addGlobalScope('order', function (Builder $builder) {
            $builder->orderBy('id', 'desc');
        });
    }
}

src/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\AWSCloudWatch;
use App\Http\Requests\UserRequest;
use App\User_settings;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;
use Illuminate\Http\Request;

use App\Exports\PharmacyDataExport;
use Maatwebsite\Excel\Facades\Excel;
use Mail;

class UserController extends Controller
{
    /**
     * Display a listing of the users
     *
     * @param  \App\User  $model
     * @return \Illuminate\View\View
     */
    public function index(User $model)
    {
        return view('users.index', ['users' => $model->where('status', '!=', 2)->paginate(15)]);
    }

    public function nonwholesalers(User $model)
    {
        return view('users.non-wholesalers', ['users' => $model->where('user_state', 1)->paginate(15)]);
    }

    public function export()
    {
        return Excel::download(new PharmacyDataExport, 'PharmacyRegistrationData.csv', \Maatwebsite\Excel\Excel::CSV, [
            'Content-Type' => 'text/csv',
        ]);
    }
    /**
     * Show the form for creating a new user
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(UserRequest $request, User $model)
    {
        $user = $model->create($request->merge(['password' => Hash::make($request->get('password'))])->all());
        $user->assignRole('User');

        return redirect()->route('user.index')->withStatus(__('User successfully created.'));
    }

    /**
     * Show the form for editing the specified user
     *
     * @param  \App\User  $user
     * @return \Illuminate\View\View
     */
    public function edit(User $user)
    {
        return view('users.edit', compact('user'));
    }

    public function editUser($id){

        $user = User::where('id', $id)->first();
        return view('users.edit', compact('user'));

    }

    /**
     * Update the specified user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UserRequest $request, User  $user)
    {
        $user->update(
            $request->merge(['password' => Hash::make($request->get('password'))])
                ->except([$request->get('password') ? '' : 'password']
        ));

        return redirect()->route('user.index')->withStatus(__('User successfully updated.'));
    }

    public function active($id){

        $settings = User_settings::where('user_id', $id)->first();
        $ruleName = $settings->ruleId;
        $cloudWatch = new AWSCloudWatch([]);
        $cloudWatch->enableRule($ruleName);

        //@TODO: Need to Target update as per user settings.

        User::where('id', $id)->update(['status' => 1]);
        return redirect()->route('user.index')->withStatus(__('User successfully Activated.'));
    }

    public function inactive($id){

        $settings = User_settings::where('user_id', $id)->first();
        $ruleName = $settings->ruleId;
        $cloudWatch = new AWSCloudWatch([]);
        $cloudWatch->disableRule($ruleName);

        //@TODO: Need to Target update as per user settings.

        User::where('id', $id)->update(['status' => 0]);
        return redirect()->route('user.index')->withStatus(__('User successfully Inactive.'));
    }

    public function search(Request $request){
        $keyword = $request->search;
        $users = User::where('status', '!=', 2)->where('pharmacy_phone', 'like', '%' . $keyword . '%')->paginate(15);
        return view('users.index', compact('users', 'keyword'));
    }


    public function delete($id){

        $settings = User_settings::where('user_id', $id)->first();
        $ruleName = $settings->ruleId;
        $cloudWatch = new AWSCloudWatch([]);
        $cloudWatch->disableRule($ruleName);

        //@TODO: Need to Target update as per user settings.

        User::where('id', $id)->update(['status' => 2]);
        return redirect()->route('user.index')->withStatus(__('User successfully Deleted.'));
    }

    /**
     * Remove the specified user from storage
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(User  $user)
    {
        $user->delete();

        return redirect()->route('user.index')->withStatus(__('User successfully deleted.'));
    }

    public function info($id){

        $user = User::find($id);


        if($user->user_state == 1)
            return redirect()->route('register.message', ['id' => $user->id]);

        return view('frontend.register-info', compact('user'));

    }

    public function store_info(Request $request){

        $info = $request->except('_token', 'user_id', 'pbs');
        $info['pharmacy_phone'] = preg_replace('/\s+/', '', $info['pharmacy_phone']);
        User::where('id', $request->user_id)->update($info);
        $user = User::find($request->user_id);

        $userName = $user->name;
        $userEmail = $user->email;
        $data['name'] = $user->name;
        $data['days'] = 2;

        if (env('MAIL_SEND')) {
            Mail::send('email_templates.accountconfirmation', $data, function ($message) use ($userEmail, $userName) {
                $message->to($userEmail, $userName)->subject
                ('Account Activated');
            });
        }

       // auth()->login($user, true);
        return redirect()->route('user.login')->withStatus(__('Your account is activated, please login to continue.'));
    }

    public function messageView($id){
        User::where('id', $id)->update(['user_state' => 1, 'status' => 0]);
        $message = 'Other wholesalers are not supported at this stage, we will inform you once they are supported';
        return view('frontend.messages', compact('message'));
    }

    public function agreementPdf(){
        $user = User::find(auth()->user()->id);
        $pdf = \PDF::loadView('pdf.saas_agreement', compact('user'));
        return $pdf->download('saas_services_agreement.pdf');
    }

}

src/resources/views/users/create.blade.php
@extends('layouts.app', ['title' => __('User Management')])

@section('content')

    {{--@include('users.partials.header', ['title' => __('Add User')])   --}}
    @include('layouts.headers.cards')
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('User Management') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('user.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('user.store') }}" autocomplete="off">
                            @csrf
                            
                            <h6 class="heading-small text-muted mb-4">{{ __('User information') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Name') }}</label>
                                    <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Name') }}" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-email">{{ __('Email') }}</label>
                                    <input type="email" name="email" id="input-email" class="form-control form-control-alternative{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="{{ __('Email') }}" value="{{ old('email') }}" required>

                                    @if ($errors->has('email'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('email') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-password">{{ __('Password') }}</label>
                                    <input type="password" name="password" id="input-password" class="form-control form-control-alternative{{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder="{{ __('Password') }}" value="" required>
                                    
                                    @if ($errors->has('password'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('password') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label class="form-control-label" for="input-password-confirmation">{{ __('Confirm Password') }}</label>
                                    <input type="password" name="password_confirmation" id="input-password-confirmation" class="form-control form-control-alternative" placeholder="{{ __('Confirm Password') }}" value="" required>
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

src/resources/views/users/edit.blade.php
@extends('layouts.app', ['title' => __('User Management')])

@section('content')
    @include('users.partials.header', ['title' => __('Edit User')])   

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('User Management') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('user.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('user.update', $user) }}" autocomplete="off">
                            @csrf
                            @method('put')

                            <h6 class="heading-small text-muted mb-4">{{ __('User information') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Name') }}</label>
                                    <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Name') }}" value="{{ old('name', $user->name) }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-email">{{ __('Email') }}</label>
                                    <input type="email" name="email" id="input-email" class="form-control form-control-alternative{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="{{ __('Email') }}" value="{{ old('email', $user->email) }}" required>

                                    @if ($errors->has('email'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('email') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-password">{{ __('Password') }}</label>
                                    <input type="password" name="password" id="input-password" class="form-control form-control-alternative{{ $errors->has('password') ? ' is-invalid' : '' }}" placeholder="{{ __('Password') }}" value="">
                                    
                                    @if ($errors->has('password'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('password') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label class="form-control-label" for="input-password-confirmation">{{ __('Confirm Password') }}</label>
                                    <input type="password" name="password_confirmation" id="input-password-confirmation" class="form-control form-control-alternative" placeholder="{{ __('Confirm Password') }}" value="">
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

src/resources/views/users/index.blade.php
@extends('layouts.app', ['title' => __('User Management')])

@section('content')
    @include('layouts.headers.cards')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-md-12 col-sm-12 col-lg-4 col-xl-6">
                                <h3 class="mb-0">{{ __('Users') }}</h3>

                            </div>
                            <div class="col-md-12 col-sm-12 mt-2 mt-md-2 col-lg-4 text-right col-xl-3">
                                <form method="post" action="{{ route('user.search') }}" class=" navbar-search-light form-inline mr-sm-3" id="navbar-search-main">
                                    @csrf
                                    <div class="form-group mb-0">
                                        <div class="input-group input-group-alternative input-group-merge">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fas fa-search"></i></span>
                                            </div>
                                            <input class="form-control" value="{{ isset($keyword) ? $keyword : '' }}" name="search" placeholder="Search" type="text">
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="col-md-12 col-xs-12 text-md-left col-lg-4 mt-2 mt-md-2 text-xs-left text-lg-right col-xl-3">
                                <a href="{{ route('user.export') }}" class="btn btn-sm btn-primary">{{ __('Export Users') }}</a>
                                <a href="{{ route('user.create') }}" class="btn btn-sm btn-primary">{{ __('Add user') }}</a>
                            </div>
                        </div>
                    </div>

                    

                    @include('layouts.status.success')

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('Name') }}</th>
                                    <th scope="col">{{ __('Email') }}</th>
                                    <th scope="col">{{ __('Pharmacy Name') }}</th>
                                    <th scope="col">{{ __('Pharmacy Phone') }}</th>
                                    <th scope="col">{{ __('Role') }}</th>
                                    <th scope="col">{{ __('Creation Date') }}</th>
                                    <th scope="col">{{ __('Status') }}</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                    <tr>
                                        <td> <?php echo $user->name ? $user->name : '<i>NULL</i>'; ?> </td>
                                        <td>
                                            <a href="mailto:{{ $user->email }}">{{ $user->email }}</a>
                                        </td>
                                        <td> <?php echo $user->pharmacy_name ? $user->pharmacy_name : '<i>NULL</i>'; ?> </td>
                                        <td> <?php echo $user->pharmacy_phone ? $user->pharmacy_phone : '<i>NULL</i>'; ?> </td>
                                        <td> <?php echo $user->role ? $user->role : '<i>NULL</i>'; ?> </td>
                                        <td>{{ $user->created_at->format('d/m/Y H:i') }}</td>
                                        <td>{{ ($user->status == 1) ? "Active": "Inactive"  }}</td>
                                        <td class="text-right">
                                            <div class="dropdown">
                                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                    @if ($user->id != auth()->id())
                                                        {{--<form action="{{ route('user.destroy', $user) }}" method="post">--}}
                                                            {{--@csrf--}}
                                                            {{--@method('delete')--}}
                                                            {{----}}
                                                            {{--<a class="dropdown-item" href="{{ route('user.edit', $user) }}">{{ __('Edit') }}</a>--}}
                                                            {{--<button type="button" class="dropdown-item" onclick="confirm('{{ __("Are you sure you want to delete this user?") }}') ? this.parentElement.submit() : ''">--}}
                                                                {{--{{ __('Delete') }}--}}
                                                            {{--</button>--}}
                                                        {{--</form>    --}}

                                                        @if($user->status == 1)
                                                            <a class="dropdown-item" href="{{ route('user.inactive', ['id' => $user->id]) }}">{{ __('Inctive') }}</a>
                                                        @elseif($user->status == 0)
                                                            <a class="dropdown-item" href="{{ route('user.active', ['id' => $user->id]) }}">{{ __('Active') }}</a>
                                                        @endif
                                                        <a class="dropdown-item" href="{{ route('user.edit', ['id' => $user->id]) }}">{{ __('Edit') }}</a>
                                                        <a class="dropdown-item" href="{{ route('user.delete', ['id' => $user->id]) }}">{{ __('Delete') }}</a>
                                                    @else
                                                        <a class="dropdown-item" href="{{ route('profile.edit') }}">{{ __('Edit') }}</a>
                                                    @endif
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                            {{ $users->links() }}
                        </nav>
                    </div>
                </div>
            </div>
        </div>
            
        @include('layouts.footers.auth')
    </div>
@endsection